In [10]:
import numpy as np
with open("ex6.txt","r") as f:
    data = [line.split('\n')[0] for line in f]

In [11]:
class point():
    def __init__(self,x,y,id_=None):
        self.x = x
        self.y = y
        self.id = id_
    

In [12]:
data_ = [line.split(', ') for line in data]

In [13]:
data__ = [ [int(i) for i in line] for line in data_ ]

In [58]:
points = [point(line[0],line[1],i) for i,line in enumerate(data__)]

In [48]:
points = [point(1,0,0),point(0,1,1),point(4,5,2),point(5,5,3), point(7,7,4)]

In [15]:
def l1norm(x1,x2):
    return abs(x1.x - x2.x) + abs(x1.y - x2.y)

In [22]:
y_max = 350
x_max = 350
min_id_matrix = np.zeros((x_max,y_max))
                         
for i in range(x_max):
    for j in range(y_max):
        distances = []
        c = point(i,j)
        for p in points:
            distances.append(l1norm(c,p))
        d_np = np.array(distances)
        if len(np.argwhere(d_np == np.min(d_np)).flatten()) > 1:
            min_id_matrix[i][j] = -1
        else:
            min_id = np.argmin(distances)
            min_id_matrix[i][j] = min_id

            boundary_ids = (list(min_id_matrix[-1,:]) 
                            + list(min_id_matrix[:,-1]) 
                            + list(min_id_matrix[0,:]) 
                            + list(min_id_matrix[:,0])
                           )


unique_boundary_ids = np.unique(boundary_ids)

unique, counts = np.unique(min_id_matrix.flatten(), return_counts=True)
dictionary = dict(zip(unique, counts))

for key in unique_boundary_ids:
    del dictionary[key] 
    
values = list(dictionary.values())
keys = list(dictionary.keys())

print(keys[np.argmax(values)])
print(np.max(values))


34.0
4186


In [55]:
min_id_matrix
print(keys[np.argmax(values)])
print(np.max(values))

3.0
11


In [56]:
plot_p = np.zeros((10,10))
for p in points:
    plot_p[p.x][p.y] = 9#f"{p.id}"
        

In [57]:
plot_p

array([[0., 9., 0., 0., 0., 0., 0., 0., 0., 0.],
       [9., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 9., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 9., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
y_max = 350
x_max = 350
threshold = 10000
min_id_matrix = np.zeros((x_max,y_max))
sum_matrix = np.zeros((x_max,y_max))
safe_matrix = np.zeros((x_max,y_max))

for i in range(x_max):
    for j in range(y_max):
        distances = []
        c = point(i,j)
        for p in points:
            distances.append(l1norm(c,p))
        d_np = np.array(distances)
        sum_matrix[i][j] = sum(distances)
        
        if len(np.argwhere(d_np == np.min(d_np)).flatten()) > 1:
            min_id_matrix[i][j] = -1
        else:
            min_id = np.argmin(distances)
            min_id_matrix[i][j] = min_id

            boundary_ids = (list(min_id_matrix[-1,:]) 
                            + list(min_id_matrix[:,-1]) 
                            + list(min_id_matrix[0,:]) 
                            + list(min_id_matrix[:,0])
                           )


unique_boundary_ids = np.unique(boundary_ids)

unique, counts = np.unique(min_id_matrix.flatten(), return_counts=True)
dictionary = dict(zip(unique, counts))

for key in unique_boundary_ids:
    del dictionary[key] 
    
values = list(dictionary.values())
keys = list(dictionary.keys())

print(keys[np.argmax(values)])
print(np.max(values))

safe_matrix[sum_matrix < threshold] = 1

34.0
4186


In [60]:
sum_matrix

array([[19623., 19573., 19523., ..., 17483., 17529., 17577.],
       [19573., 19523., 19473., ..., 17433., 17479., 17527.],
       [19523., 19473., 19423., ..., 17383., 17429., 17477.],
       ...,
       [17239., 17189., 17139., ..., 15099., 15145., 15193.],
       [17287., 17237., 17187., ..., 15147., 15193., 15241.],
       [17335., 17285., 17235., ..., 15195., 15241., 15289.]])

In [61]:
sum(safe_matrix.flatten())

45509.0

In [62]:
safe_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])